package com.gzf01.rxzsmbclient.model.sqldao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gzf01.rxzsmbclient.entity.Link;

import com.gzf01.rxzsmbclient.model.sqldao.LinkDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig linkDaoConfig;

    private final LinkDao linkDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        linkDaoConfig = daoConfigMap.get(LinkDao.class).clone();
        linkDaoConfig.initIdentityScope(type);

        linkDao = new LinkDao(linkDaoConfig, this);

        registerDao(Link.class, linkDao);
    }
    
    public void clear() {
        linkDaoConfig.clearIdentityScope();
    }

    public LinkDao getLinkDao() {
        return linkDao;
    }

}
